convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"a" a.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"b" b.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"c" c.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"d" d.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"e" e.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"f" f.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"g" g.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"h" h.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"i" i.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"j" j.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"k" k.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"l" l.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"m" m.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"n" n.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"o" o.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"p" p.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"q" q.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"r" r.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"s" s.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"t" t.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"u" u.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"v" v.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"w" w.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"x" x.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"y" y.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"z" z.png
