convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"A" A.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"B" B.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"C" C.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"D" D.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"E" E.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"F" F.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"G" G.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"H" H.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"I" I.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"J" J.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"K" K.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"L" L.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"M" M.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"N" N.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"O" O.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"P" P.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"Q" Q.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"R" R.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"S" S.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"T" T.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"U" U.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"V" V.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"W" W.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"X" X.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"Y" Y.png
convert -background none -fill white -font Handwriting-Regular.ttf -pointsize 300 label:"Z" Z.png
